### PR TITLE
Styling like new sphinx theme

### PR DESCRIPTION
**Pull request by Shekharrajak**

### CODE REVIEW

**Comment by Shekharrajak** [comment]
Not able to deploy the static content into surge because it is too large.

**Comment by rgommers** [comment]
> Not able to deploy the static content into surge because it is too large.

what's the size limit, and how much are we over it?

**Comment by Shekharrajak** [comment]
> what's the size limit, and how much are we over it?

Actually this repo size is large because it has zip, pdfs files and old version docs source. Surge command is only showing "too large to deploy".

**Comment by Shekharrajak** [comment]
May be we can have separate repo for styling/CSS, JS and images and all the repos will refer to it. i.e. `numpy/doc`, scipy-sphinx-theme will be having submodule to use the CSS, JS, images. Wih this approach we will get rid of redundancy to do same change in different repo/UI page.

**Comment by mattip** [comment]
Are there parts of this that are not appopriate for [scippy-sphinx-theme](https://github.com/scipy/scipy-sphinx-theme)?  It would be nice to avoid opening yet another repo

**Comment by rgommers** [comment]
+1 for keeping things in one place, I'd be happy with either using `scipy-sphinx-theme` as a submodule for that or a new repo otherwise.

**Comment by Shekharrajak** [comment]
> Are there parts of this that are not appopriate for [scipy-sphinx-theme](https://github.com/scipy/scipy-sphinx-theme)? It would be nice to avoid opening yet another repo

Actually there is no submodule right now and css written in this repo is same as scipy-sphinx-theme css (just copy). I think we can directly use the link for the css like: 

```
  <link rel="stylesheet" href="https://raw.githubusercontent.com/Shekharrajak/scipy-sphinx-theme-v2/master/custom_sphinx_theme/static/css/preloader.css" type="text/css" />

```

We need to make sure the theme repo folder structure not changed and if changed then we need to do change the link accordingly.

**Comment by mattip** [comment]
Since this is not a stand-alone repo rather it is deployed at numpy.org/docs, could we use a relative link to the appropriate numpy.org location?

**Comment by Shekharrajak** [comment]
> at numpy.org/docs, cou

Yeah, in that case we can have repo something like `numpy/UI` and all the CSS/JS/images will go there and can be used like in this repo we can access basic.css file: https://numpy.org/doc/_static/basic.css

Or we can have separate repo for CSS, JS and images like: `numpy/CSS` , `numpy/JS`, `numpy/images`

**Comment by mattip** [comment]
I must be confused. Why are we styling this repo at all? It was meant to be a static archive of the documents for each minor (1.13, 1,14, 1.15 ...) release. If the problem is that the archived html does not point to the correct numpy.org-wide style sheets, maybe we should be changing the `make html` in the numpy repo to fix that, then regenerate the content here with the updated links and recreate this repo from scratch.

Creating repos for the html style is, in my opinion, an anti-pattern, that is what the sphinx theme is for, no?

With that, it may be easier to play with this repo for experimenting with theming the site, but the intent should be that this repo remain, as much as possible, a "dead" archive with no need for maintenance or periodic updates.

**Comment by Shekharrajak** [comment]
If I understood correctly then

> I must be confused. Why are we styling this repo at all? It was meant to be a static archive of the documents for each minor (1.13, 1,14, 1.15 ...) release.

Yes, all the versions folder are generated we are not touching those generated static html files/folders.

I am talking about the landing page [index.html - uses _static/css and js ](https://github.com/numpy/doc/blob/master/index.html#L9), I think it is not generated and it is same as scipy-sphinx-theme css (but not using the submodule instead it is put in _static folder).

So if we change the theme css (in future) it should be aligned with all the subpages like numpy/doc, numpy/neps ,.. and we need not have to change in multiple repos.

Am I correct?

**Comment by mattip** [comment]
Got it, thanks. So if index.html page would  numpy.org/_static or numpy.org/devdocs/_static we can just delete that _static directory here.

**Comment by Shekharrajak** [comment]
> Got it, thanks. So if index.html page would use numpy.org/_static or numpy.org/devdocs/_static we can just delete that _static directory here.
> 
> Edit: add "use"

Yeah! that will be good. We can use the css directly from the link: https://raw.githubusercontent.com/numpy/devdocs/master/_static/scipy.css 

About neps: `numpy/neps` is  auto generated and uses the theme directly so we don't have to do anything there.

**Comment by Shekharrajak** [comment]
Isn't it better to make it sphinx docs and use the theme like https://github.com/numpy/neps ? 

Once we migrate it to sphinx doc then we don't need to care much about styling for different subpages. 

What do you people think?

**Comment by rgommers** [comment]
I'll just add a few screenshots of how it looks right now to help the discussion:

image


image

A few thoughts:
- It definitely looks a lot better than the old site. 
- I don't think we can deploy it before we finalize the new numpy.org site, because the links will be broken.
- https://github.com/numpy/neps is auto-generated, so I'm not sure how it's helpful. It seems like the discussion about using the Sphinx theme here is right, better than adding too much here.

**Comment by Shekharrajak** [comment]
> * https://github.com/numpy/neps is auto-generated, so I'm not sure how it's helpful. It seems like the discussion about using the Sphinx theme here is right

Thanks for review.
Yes! My proposal is to make it sphinx based very similar to the neps (which is auto generated using the theme).

**Comment by Shekharrajak** [comment]
Refer: https://github.com/numpy/doc/pull/2

**Comment by Shekharrajak** [comment]
As we discussed we can have sphinx theme based site. I have tried out it here: https://github.com/Shekharrajak/versions

I have noted down few things:

* Size of the PDF and zip file is large, so to make the website faster we can have it in some cloud storage and just link it into the site like AWS S3 storage.
* We also have bunch of builds for the old versions but those files are not minified. We can reduce the overall file/folder size by minifying it.

WDYT?

**Comment by Shekharrajak** [comment]
I am trying to move numpy.org static page to sphinx based page. Here is the repo for the same: https://github.com/Shekharrajak/versions I tried to put it in surge for the demo URL but because of large file it is not happening: https://github.com/Shekharrajak/versions/issues/2 I have removed most of the files just for demo here: http://numpy-versions-0.surge.sh/ 

So now we will just maintain the scipy sphinx theme for UI across all the subpages like: NEPs, doc, devdoc so that styling and UI is same and we don’t have to do redundant work.

WDYT?

**Comment by mattip** [comment]
In my opinion there are advantages to using a non-sphinx based framework for numpy.org, but remaining with sphinx for numpy.org/doc. Maybe we can make many of the theme elements (css, template principles) consistent across the two sites without requiring using the same tool.

**Comment by mattip** [comment]
Is the size of the pages on this site really worth the effort to minimize or move to another hosting solution? Since github pages is hosting, as long as we stay within their generous limits we should have no problems.

> So now we will just maintain the scipy sphinx theme for UI across all the subpages like: NEPs, doc, devdoc so that styling and UI is same and we don’t have to do redundant work.

+1. I think the easiest place to start is on the devdoc/nep site which is part of the numpy/numpy repo. Once the new theme is deployed there, we can rebuild this site using it.

**Comment by Shekharrajak** [comment]
> Is the size of the pages on this site really worth the effort to minimize or move to another hosting solution? Since github pages is hosting, as long as we stay within their generous limits we should have no problems.

I see that https://numpy.org/doc is pretty fast. But when we try to build it, we get the heavy build to deploy in free servers. Even it takes time locally (isn't it?). 
But yeah it works smoothly for github pages.

**Comment by Shekharrajak** [comment]
> +1. I think the easiest place to start is on the devdoc/nep site which is part of the numpy/numpy repo. Once the new theme is deployed there, we can rebuild this site using it.

NEPs are auto generated in numpy/numpy repo and uses the same theme whatever is used for `devdoc` (numpy documentation).  I tried it here only: https://github.com/numpy/numpy/pull/14648#issuecomment-557569834 Demo link is : http://generated-numpy-neps-sphinx2.surge.sh/

**Comment by rgommers** [comment]
I think the Surge deploy won't work due to repo size, that's hard to avoid. I'm happy to just not have an auto-build/deploy for PRs, and do all testing locally. This repo anyway gets updated rarely (once per release).

**Comment by rgommers** [comment]
>     * Size of the PDF and zip file is large, so to make the website faster we can have it in some cloud storage and just link it into the site like AWS S3 storage.

This would undo all the work @mattip did to get the doc builds into this repo. I'd rather just keep that aspect as is, and only change the Sphinx theme.

**Comment by Shekharrajak** [comment]
> I think the Surge deploy won't work due to repo size, that's hard to avoid. I'm happy to just not have an auto-build/deploy for PRs, and do all testing locally. This repo anyway gets updated rarely (once per release).

Thanks for the suggestion.

**Comment by Shekharrajak** [comment]
Please have a look the sphinx based version of this repository: https://github.com/Shekharrajak/versions

**Comment by mattip** [comment]
Will the theme be deployed to the numpy.org site and/or devdoc site?

**Comment by Shekharrajak** [comment]
> Will the theme be deployed to the numpy.org site and/or devdoc site?

numpy.org will be hugo based site and all other documentation related pages - devdoc, doc, neps will be sphinx based site.

**Comment by mattip** [comment]
It would be good to design the layout of numpy.org so there is one source-of-truth for the static content of the site (`_static` directory: css, icons, javascript ...) for all the sites, that would lend a unified look to the site rather than relying on each repo to have a copy of the sphinx theme submodule and deploying that copy

**Comment by Shekharrajak** [comment]
> of numpy.org so there is

Yeah! It would be good if we have common css/js file.

**Comment by mattip** [comment]
Closing. HEAD had moved to the pydata_sphinx_theme from Pandas.

**Pull request closed without merging**
