### PR TITLE
add 2.0 documentation and make it the stable version

### PR DESCRIPTION
**Pull request by mattip**
I followed the instructions in the Makefile, except for the force push.

### CODE REVIEW

**Comment by mattip** [comment]
cc @charris

**Comment by mattip** [comment]
Beyond adding the 2.0 files, I also
- edited the index.html
- added the version to version.json
- used the `python update.py` script to update the old version warning, which I do not see anymore even on the existing documentation (???)
- changed the `stable` symbolic link to point to 2.0

**Comment by melissawm** [comment]
The version warning should be provided by the pydata sphinx theme now - so we should add 

```
html_theme_options = {
    ...
    "show_version_warning_banner": True,
}
```

to conf.py (see https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/announcements.html#version-warning-banners - this page will actually show the functionality at the top)

**Comment by mattip** [comment]
> The version warning should be provided by the pydata sphinx theme now

Let's do that in a follow on, this should be merged soon

**Comment by melissawm** [comment]
The stable docs will have to be rebuilt for that. If that's not an issue I'm happy to do It in a follow up 👍

**Comment by mattip** [comment]
I don't think rebuilding is an issue. More of a problem is getting the warning into the 1.26 and earlier docs.

**Comment by charris** [comment]
Lets just get this in.

**Comment by melissawm** [comment]
I just submitted a PR to fix the version switcher as well: https://github.com/numpy/doc/pull/25

I'll send another to turn on the version warning banner for the newer versions of the docs.

**Comment by charris** [comment]
@melissawm Is there any reason not to merge this? If not, hit the merge button.

**Comment by melissawm** [comment]
Please merge, we can fix the warning banner later. Just make sure to also merge the version switcher json update over at #25

**Comment by charris** [comment]
Melissa, I want _you_ to merge. You will feel better after :)

**Pull request merged**
