### PR TITLE
Update building.html #23786

### PR DESCRIPTION
**Pull request by DhavalParmar61**

### CODE REVIEW

**Comment by DhavalParmar61** [comment]
@mattip Updated documentation  at doc/1.24/user/building.html based on issue #23786 and  your suggestions

**Comment by mattip** [comment]
Replaces #13. LGTM.
@melissawm thoughts?

**Comment by melissawm** [comment]
Ok, that sounds good to me. My thinking is we might have wanted to preserve the old link but this works better and reduces confusion, so +1 from me

**Comment by mattip** [comment]
Thanks @DhavalParmar61

**Pull request merged**
