### PR TITLE
devdoc build using the scipy-sphinx-theme-v2

### PR DESCRIPTION
**Pull request by Shekharrajak**
Using the theme : https://github.com/Shekharrajak/scipy-sphinx-theme-v2
Related PR: https://github.com/numpy/numpy/pull/14648

### CODE REVIEW

**Comment by rgommers** [comment]
There's a ton of SVG images for math expressions in this PR. I think you still have `pngmath` or `imgmath` in your config somewhere, it should be changed to using `mathjax` so we get rendered math in the browser rather than static images.

I don't think the rest of this PR is reviewable before that is fixed, it has 3000+ changed files.

**Comment by Shekharrajak** [comment]
I have removed plugins sphinx math and svg which where generating images in _image/math folder. I am using js directly [here](https://github.com/Shekharrajak/scipy-sphinx-theme-v2/blob/master/custom_sphinx_theme/head.html#L59) instead of sphinx plugin so they are not needed. 

I have removed the build related hidden files as well.

**Comment by rgommers** [comment]
Ah the link above it moved, it's loaded directly in the html: https://github.com/scipy/scipy-sphinx-theme-v2/commit/2f8cb2e5bea0c838f8fd2b3ab6a026c006881c42

I suspect that this is the more correct way of doing it: https://github.com/scipy/scipy/blob/master/doc/source/conf.py#L44. I think `mathjax` config belongs in the config of the project using the theme, rather than hardcoded in the theme. The old Sphinx theme doesn't have anything.

This PR also still has thousands of `.doctree` files, do those need to be there?

**Comment by Shekharrajak** [comment]
Thanks @rgommers! I will try with plugin once again (last time I find some issue with generated the latex version for the equations, so I tried to add the JS in script itself).

**Comment by Shekharrajak** [comment]
> Ah the link above it moved, it's loaded directly in the html: [scipy/scipy-sphinx-theme-v2@2f8cb2e](https://github.com/scipy/scipy-sphinx-theme-v2/commit/2f8cb2e5bea0c838f8fd2b3ab6a026c006881c42)
> 
> I suspect that this is the more correct way of doing it: https://github.com/scipy/scipy/blob/master/doc/source/conf.py#L44. I think `mathjax` config belongs in the config of the project using the theme, rather than hardcoded in the theme. The old Sphinx theme doesn't have anything.
> 
> This PR also still has thousands of `.doctree` files, do those need to be there?

Fixed it here : https://github.com/scipy/scipy-sphinx-theme-v2/pull/73

**Comment by mattip** [comment]
Closing. HEAD had moved to the pydata_sphinx_theme from Pandas.

**Pull request closed without merging**
